#NAME: Wai Yan (Will) Htun
#EMAIL: willhtun42@gmail.com
#ID: 104941153

.SILENT:

default:
	
clean:
	rm *.tar.gz

dist:
	tar -czf lab4a-104941153.tar.gz Makefile README connected.png build_run.png copy.png git.png my_beaglebone.png
